apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
data:
  bash_aliases: |
    {{- .Values.config.bashAliases | nindent 4 }}
  openclaw.json: |
    {{- .Values.config.openclawJson | nindent 4 }}
