apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mssql-sa-password
  namespace: default
spec:
  encryptedData:
    MSSQL_SA_PASSWORD: AgABEI+4qw62t6yoANj4REcoGobG3kW2XQlm1L+o+I4hmh/59QU8IHrIVAGOKwjsKFeQM4Uk5EcMd0DRwUGjDYMYjZ5FtxDhxW0ySPwiY2vKZd/VxclT9kMnqh8IYjggco87kksMPWgvBjxmLtuyMmuxZKbMgohhUIK8kdjEuIbv54XACnk0D2dT8sonY0zFE+o3MIJtlYs373QIyEtAzlOeP8e70gNIPCSgOPKHNvO+NzF2GgkK7wEcjSyNoWXbJ6c3ZLX6+Zqs9RG70TQKv4NhTB1X9NnQJ4f5Hhb8DCrvufZ5SIwu3e1H7i/Yifit7AcycDTSAY8WE6mB9N5b9KsHk/Lugy4+mVaz4nVPmLJrT00JkwDqf18k6QUbWhBhE9iA3nYdraj3HhDem2r2ZggmcatNDMx5kOgcINDc7sXvGprYjUgGXYpfFJj1sdidOVy/1+2/4KG043NNNlLqaSspews2ze986h25YDHT97gJv60HHD0CoS71daNRYuOgMdzASWWBhog7MBJD8ZEERdyqxB5JMcN/l/+oN/RSwxxnr59BrDe7VsE9MCKItCIIzzDscYUHc3QjyYlOGyv9Wmp4oUWgNMctdCr1AqLLtSf8+sur2MkU9lJXYind/ANQHh60jKOxb4+0yTXhZb3a9I0stS1YeoLjB4dbZEczZ8KUFTTBqQvB2vxKwiO6EKm+7mzkyM688wLqHoi/xxxnoGfAxv2zz9d4JAQ1ICOB9N4WJMtVHVKLifH7VuCOQ505cC/0j4esOycJ4WvYps+AzPB0c7bDAltCscFq5ocgyemoxhPuE9JbMCxivfsQ7q0bq/p+cCcVv7z1gWUJdFgwKHMdr9MRJ2wAy9BoNWSUjemGNQ==
  template:
    metadata:
      name: mssql-sa-password
      namespace: default
    type: Opaque