apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mssql-sa-password
  namespace: mssql
spec:
  encryptedData:
    MSSQL_SA_PASSWORD: AgDJjI3Z/mhwmBu76AOq+sppNxX/LA9oRs0jTfy/W+4mt6BiQwISpRAQ/+XJqPPw9ntKWywUVQFuuUi+R8xrIaJC0uqR3cupk0tHJRNJKgDNpvVNf0iIiINRcBKXpzgYdK2CdSCPYSQM0DFvEQZyiZqsxQTz2hbumL+IHrvT8upemoQw4EvwveNbni/P1UU9pZdq2sT2bFIsV9CdwwSQ2BaR7/HR0DthxlPnR5TU+q594MJtQf9WBoOn4X+KN89BsECkq3u/2FX23iwOe0YYigZlW18zzwQxSP6D5aSZp0GrtZqrYG2yIf6jcWuIQCKhUEUmZ+l6UZrlwGi1eCAzej3Kf5QzANiQiCoYf4GhlJ8fU/ef65XS/m8sT4AjvnA/eSmHFjOFXtAhl/hMAYCP+lTnH+SGpOA9rSUwucWtFdFDffuJzUwaOuWBW7Pnq3Fp2dPQvCJag5qC/kaVjdQnpFdb0bGAayVDKzG27A1juHoNpXzRI4RKSk1wz6bSBwgOspm0nc/2znaw/Uoou735HV/RS7FC/gH64iHbSYQCbGxzsijWzLD7cMy0juaywuITD/UAZki7z7FEfj5Kd8boJAKM97e62NdsaFYdMBMOLrcELmJACk2nNq+vhaQePJK/v65wURF0nv2CI1cfrlZUPJExJ2dwxhIRVR9M+bh94nodmsZ+fMq+accmV+FUTYgQwBtTVzj8AoTwAiJ3vqKNM1aCAUVDYL6vPcIC0z2tOjbeiq1W/k5aBwgJr/czpS2WvzXrB/85CS+yGuzVUue7YXnByHofUKxv6fh6fKckUzfgEc+DR80So4DZ1NFJStYsORpLmvqkt5H1SM/bwTAGpJsadB1pO74mbv4q6ZZEXloEjg==
  template:
    metadata:
      name: mssql-sa-password
      namespace: mssql
    type: Opaque