apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgBk11ZRLoAoaijO9Y+HBLBtKXmDjxZ3Dq0z1uZny/WYnVg0Vsb6LW5fhrIZvBv32cG/yhLU3rPLLJI7bHREt98hXidu3pXtZs6xny4W4S5Uo7KO0Rj3S2rJaqeTz24gOmv6WJl2pB/QIYBO17/TElLMNUW7kTEqY19OK+3JzB4Llnu0znMiRNFFDpVkEt7M/WC5cRD/tUiPt7FLrmzkp1PpwaJMXTEo9+QsLvJYcueZpERLjbXt8VfkDOVYynYVn+Odunb747Jb7uJXktSz4bF8svC7u80RDIAamJkdGEpqnDKOo1JdIdRXtLB5vFxQXP3GaG+aGl9InJwxLGuqXp7D/OwYONbW5n/EE+Lv0Q7zGJ0Pq2/4XNI9S1sEKQWCnxlDhqRE1qOnJtJSMzuyeBCk3sWBtvHDqtTegbUhwOYUzoN0hVH8vvROOCBAx6hQm642hosdSMciPnhM6tdNmF1NOBqNbmFUOHPOjp+dzPJhrgFcgkusAw1pe8TH+B1KQGH/YuISs97+oAF5GxNSCS9me8Iah759Q1VF2f29ZR5zNHvq6M0WlF/UiHqrqXkaX862nnvFfsRdmf8OYMBuczKmmGpy6QnmXt7lJv7J0u7nNwveF8uiM8/z/KBCrzLQxcHBuQQan6T2dq4HXVLmiM8Ygkk29viz9qX78G7Xed8ENXjUSpEwah5PcOhUZW8cAm4Ss9c9SXalLJPAveL0pMd3InGqf4hPUoX0kxROr//4b63/7Qgzfs7uTk+BinQ0KS0kyPzssgAOu3VKhrrXk5nPbn9y4MKsRu8yUFSfnIfUqGP0OCXYiUK+phcNJ4Sbgi59BKdEyXIzKOuGaDD7RNXOimGc/U5XwP6skSAr1W3TpQ==
  template:
    metadata:
      name: harbor-admin-password
      namespace: harbor
    type: Opaque