apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-regcred
  namespace: harbor
spec:
  encryptedData:
    .dockerconfigjson: AgAbbVtpK58lBcYJbva0lxIIm6ng9fH9HQQ+1u1xal+Q17BUsQeva5DgxeAVKEVcdKY3Wt2OT8FiYiAlu2enBwEZaW/GOKJjvcOE7XY8lmBmqmgMYGxrtRQg72upWszlvLbflLUXVg7ABb9U5o3U3n3RMd77s0ZuZrntwk1PxJNqKxnvoqeqSxCa5/0k3zBKcm+g3kb32OSSe8pUdVLvEKIfCUeRs+9o8b9NO//2Oa3eQQoxiSG/pyhtw+vrgbSuf9gPPs7GmX/yUwun1w4ur/790oSnINm61WeBN/zcKpVKz/7HJvgWBKJ7G2BzHa6zzgG5Hv1uLFaDuVrxVDuv3c2JHZl2VFkx8nzue/bmICuTwkGlynKBRJSf0zXP0+8ugyqntyuTymO8NORZLG1Oizghv+KOA44wt05hg7mDsRpqIKxrSPoC66HGY7deIHStp9dTgc7xy1TOMzgyBK5qvCapQ8GaV9zpqPttcdcnYqqbT8QNSmYDMyzeoRTr/YRqzSxo1T/jmIs7eEmbxLrLQcg/OCteMAX6NXbqu7HmAICm7L0u3nemlmir2L8mQ4O4+HyRIvb8q1AElKNuzcAtIgsuK4FYOe0OJic61JosVE5m+dn+rS+6Gwgh/fxh5ygwrzOgofpo6XzC7oV5t4K+H7QXC8NDt+j6f7n+ygkdGeQtj0zHx8r9aGhUTw4a824ats7MgKILDFvuphJ9bNGz1Fq5zrRskUlR5Rc8Psoy9JZV8n58B+pONp9zC0k3phWKGNiegFIju5ygmwU8WXL0xjuzE9KibeTSDUpGX+CRaBCtL7S7mSDUK/O58WIxYrf+tvcIX99zndXtgt+stiIqKYS4jA1jPrpgeXx+wWI5xhLhLPrqPG2vJU4/4H6RiM7L4u+sa3MAJ292FFDtlZBmdB4o+A0C0z30cSs=
  template:
    metadata:
      name: harbor-regcred
      namespace: harbor
    type: kubernetes.io/dockerconfigjson