apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-regcred
  namespace: harbor
spec:
  encryptedData:
    .dockerconfigjson: AgCyPyIToTQaz+ejbjBpUxi3TuU+MR93Xg63o8sZmGCXHIKufQAMbTWZKTMMwi5NjKes9inqlVRj81H+R6pVUVgJ/MK66aoqfORoUPowlS3xeCCZnSM2fS2Ar2LjOoPZ+ruO8KC2OEBoSZYOtgLbXSmXEDHEV9sUNnaqjUk3FbcXTns83L7/RmPr0Hon2sSvbyMF4NshwvaBhrUK14QGb5qpm0YeDHpICBGsDFKmse5V+My5Vi2owPt2cukB/TAo7qOa+rsVPpGKB3PhUmHRltclWGd+TlJHicjZGV6jRBH5cHvNP+FTa57EDn2uWnt0bDMZxFBHLUqz/DXOSGelbtK5JrHStwICeHLu/kEi33fBCQlTzIBV6qOwiEJBRWTg3IK+tpe3b3vmtxJiR2BxAgKClwdtKoBv/FsaeOuiwbFd+kivhNHae3WrYAGfLysbV69BW3OU3Vs7lumDR9M3dYWKAsCP/HoxwBmGVmXw7/ms7w1/2hYEIN6swkTw0FWg+/z5CHXLOjAZGh89kMKUcQehAlHKQ80d+R0s7YyCDYd1YOFC6W+GQZOjLNDRHF+7jiI6OvSh26Gf+wrrgp8GgAgUaHc5d5QPRKRq/rBkdKly6PV3bZkdgvDXqldw5OAv5WZC9ehr41lIog0pitDvO8izyjnjLkihYMxuhGj4Vh/HZMdX14jFhIeUcjwKxstoe2uVuNZvxB3YVn5950IXe7zcBX+maH8tPkxUulLa+G5p2MYEoUe/6L7On5pGlFptPx6tmtnzM4Q3TV6BQd4NzO+09R6BVMkvwh+hV7OVJSDBEkibSv2bVJDWvXuNlukyHi++iCqH5OCIsQuKIy4qsdU0iV3YGPnxE6fEypReTZpoj8cTEKQblkdFOzGR5SoDeZCdesaibNqoNGuhaZW0OhRQXnhHuDOE0Pk=
  template:
    metadata:
      name: harbor-regcred
      namespace: harbor
    type: kubernetes.io/dockerconfigjson