apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cloudflared-tunnel-token
