apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgA9OWRQFmxv51yTCW8MqAJXQZcWKkcNGdHWWsA9n3W2QVUFJf3Y5vjhtmGJg5sNc+b+cyv1+32zPUFqOHLbfwcM5IeFGDChkqNy/5+BH9fmZdBnZylBLM94nAwyfjasiMTEPrQD+JTQ39G9K5FrljXJtkgcSNj7l7CYMB0d4eTHIyqDmA53nOqOxpc//TqoISYOUSPHwL+U2kvCvZFJzud/mu/seKmZ6xKE+uQHHpnBw8BrL1ieN7aRHhJtZ67udBsyzFATVIEDEb4T+y9GwZ2k/RO6/NvDMOgjKa9ADPaWQrx1Q2NppFmW18bes5Z6gRrLpilNP9wtpgcmkQAH45uFI3NNlp/7OtmJImCF98+vOEH172vgbhVUVmysF0IORNSu1jSVVZpxLboOlol1/HN0fu2wMgwX9+2M6G+Clsk9StEwPl2nOEHxE7Zi0riT7DZsfFMLqVbFuZUAOp+fOfhKcivqze36RxujWJOF8fTmrzpIyyD4u8sJs7nELJZvqowcEE04PZyemOPDUixVxD3cgpG4g5M2m2x7HEdWcoZMcA9nkVJdHJaOMRqQn9AGWLvksN7hjgZGYznhCStHQGyeKy6e2WQ8VCTsnKZmvkLqetHZ7TENgeoS26JBZR33dFM+csySc2HCLrliPJVhUxT0mrqmEpBQoLZC7woe1BLPKGLEj9DIKDlYUGjaT1Eg1ExR+ovk70vQpHfQ3TvisQGkm4Z27+XcjMRyu7Uy1kCtZFhB4pEMdIDihSC/nQRDelMCnxqvKeWQCTNsjQqM5O31nUd9Vb+AuhasojvyhXrllP6j1xGcvkuQYqC9GcwYkDqQqJl0rbobc5lGz9j+eRQAOjpvwlRB5TmgadvxXTyn4OWmOQxMZdNx2ZFHpw67Q1vLj548mvT3DBuKhHZHay1h1lk3TsxSgvszA0CSHIJVV+8qzzebhYZ0
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared